/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './login';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from 'ionic-angular/components/alert/alert';
import * as import10 from '@angular/http/src/http';
import * as import11 from '../../providers/auth';
import * as import12 from '../../providers/common';
import * as import13 from '@angular/core/src/metadata/view';
import * as import14 from '@angular/core/src/linker/component_factory';
import * as import15 from 'ionic-angular/components/content/content';
import * as import16 from '@angular/forms/src/directives/ng_form';
import * as import17 from '@angular/forms/src/directives/ng_control_status';
import * as import18 from 'ionic-angular/components/list/list';
import * as import19 from 'ionic-angular/components/item/item';
import * as import20 from '@angular/core/src/linker/query_list';
import * as import21 from 'ionic-angular/components/label/label';
import * as import22 from '@angular/forms/src/directives/validators';
import * as import23 from '@angular/forms/src/directives/ng_model';
import * as import24 from 'ionic-angular/components/input/input';
import * as import25 from 'ionic-angular/components/button/button';
import * as import26 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import27 from 'ionic-angular/config/config';
import * as import28 from '@angular/core/src/linker/element_ref';
import * as import29 from 'ionic-angular/components/app/app';
import * as import30 from 'ionic-angular/util/keyboard';
import * as import31 from '@angular/core/src/zone/ng_zone';
import * as import32 from 'ionic-angular/navigation/view-controller';
import * as import33 from 'ionic-angular/components/tabs/tabs';
import * as import34 from 'ionic-angular/gestures/gesture-controller';
import * as import35 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import36 from 'ionic-angular/util/form';
import * as import37 from '../../node_modules/ionic-angular/components/input/input.ngfactory';
import * as import38 from 'ionic-angular/platform/platform';
import * as import39 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import40 from '@angular/forms/src/validators';
import * as import41 from '@angular/forms/src/directives/ng_control';
import * as import42 from '@angular/forms/src/directives/control_container';
var renderType_LoginPage_Host:import0.RenderComponentType = (null as any);
class _View_LoginPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _LoginPage_0_4:import3.LoginPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_LoginPage_Host0,renderType_LoginPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-login',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_LoginPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._LoginPage_0_4 = new import3.LoginPage(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.AlertController),this.parentInjector.get(import10.Http),this.parentInjector.get(import11.Auth),this.parentInjector.get(import12.Common));
    this._appEl_0.initComponent(this._LoginPage_0_4,[],compView_0);
    compView_0.create(this._LoginPage_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.LoginPage) && (0 === requestNodeIndex))) { return this._LoginPage_0_4; }
    return notFoundResult;
  }
}
function viewFactory_LoginPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_LoginPage_Host === (null as any))) { (renderType_LoginPage_Host = viewUtils.createRenderComponentType('',0,import13.ViewEncapsulation.None,[],{})); }
  return new _View_LoginPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const LoginPageNgFactory:import14.ComponentFactory<import3.LoginPage> = new import14.ComponentFactory<import3.LoginPage>('page-login',viewFactory_LoginPage_Host0,import3.LoginPage);
const styles_LoginPage:any[] = [];
var renderType_LoginPage:import0.RenderComponentType = (null as any);
class _View_LoginPage0 extends import1.AppView<import3.LoginPage> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _Content_0_4:import15.Content;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _NgForm_7_3:import16.NgForm;
  _ControlContainer_7_4:any;
  _NgControlStatusGroup_7_5:import17.NgControlStatusGroup;
  _text_8:any;
  _el_9:any;
  _List_9_3:import18.List;
  _text_10:any;
  _el_11:any;
  /*private*/ _appEl_11:import2.AppElement;
  _Item_11_4:import19.Item;
  _ItemContent_11_5:import19.ItemContent;
  _query_Label_11_0:import20.QueryList<any>;
  _query_Button_11_1:import20.QueryList<any>;
  _query_Icon_11_2:import20.QueryList<any>;
  _text_12:any;
  _el_13:any;
  _Label_13_3:import21.Label;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  /*private*/ _appEl_16:import2.AppElement;
  _RequiredValidator_16_4:import22.RequiredValidator;
  _MinLengthValidator_16_5:import22.MinLengthValidator;
  _MaxLengthValidator_16_6:import22.MaxLengthValidator;
  _NG_VALIDATORS_16_7:any[];
  _NgModel_16_8:import23.NgModel;
  _NgControl_16_9:any;
  _NgControlStatus_16_10:import17.NgControlStatus;
  _TextInput_16_11:import24.TextInput;
  _text_17:any;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  /*private*/ _appEl_20:import2.AppElement;
  _Item_20_4:import19.Item;
  _ItemContent_20_5:import19.ItemContent;
  _query_Label_20_0:import20.QueryList<any>;
  _query_Button_20_1:import20.QueryList<any>;
  _query_Icon_20_2:import20.QueryList<any>;
  _text_21:any;
  _el_22:any;
  _Label_22_3:import21.Label;
  _text_23:any;
  _text_24:any;
  _el_25:any;
  /*private*/ _appEl_25:import2.AppElement;
  _RequiredValidator_25_4:import22.RequiredValidator;
  _MinLengthValidator_25_5:import22.MinLengthValidator;
  _MaxLengthValidator_25_6:import22.MaxLengthValidator;
  _NG_VALIDATORS_25_7:any[];
  _NgModel_25_8:import23.NgModel;
  _NgControl_25_9:any;
  _NgControlStatus_25_10:import17.NgControlStatus;
  _TextInput_25_11:import24.TextInput;
  _text_26:any;
  _text_27:any;
  _text_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _el_32:any;
  /*private*/ _appEl_32:import2.AppElement;
  _Button_32_4:import25.Button;
  _text_33:any;
  _text_34:any;
  _text_35:any;
  _text_36:any;
  _el_37:any;
  _text_38:any;
  _el_39:any;
  _text_40:any;
  _text_41:any;
  _el_42:any;
  _text_43:any;
  _text_44:any;
  _text_45:any;
  _text_46:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_21:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_23:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_26:any;
  /*private*/ _expr_27:any;
  /*private*/ _expr_28:any;
  /*private*/ _expr_29:any;
  /*private*/ _expr_30:any;
  /*private*/ _expr_31:any;
  /*private*/ _expr_32:any;
  /*private*/ _expr_33:any;
  /*private*/ _expr_34:any;
  /*private*/ _expr_35:any;
  /*private*/ _expr_36:any;
  /*private*/ _expr_37:any;
  /*private*/ _expr_38:any;
  /*private*/ _expr_39:any;
  /*private*/ _expr_40:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_LoginPage0,renderType_LoginPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','padding page-parent');
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import26.viewFactory_Content0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Content_0_4 = new import15.Content(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import29.App),this.parentInjector.get(import30.Keyboard),this.parentInjector.get(import31.NgZone),this.parentInjector.get(import32.ViewController,(null as any)),this.parentInjector.get(import33.Tabs,(null as any)));
    this._appEl_0.initComponent(this._Content_0_4,[],compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'img',(null as any));
    this.renderer.setElementAttribute(this._el_4,'src','assets/img/isi_logo.png');
    this._text_5 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_7 = this.renderer.createElement((null as any),'form',(null as any));
    this.renderer.setElementAttribute(this._el_7,'name','signinForm');
    this.renderer.setElementAttribute(this._el_7,'novalidate','');
    this._NgForm_7_3 = new import16.NgForm((null as any),(null as any));
    this._ControlContainer_7_4 = this._NgForm_7_3;
    this._NgControlStatusGroup_7_5 = new import17.NgControlStatusGroup(this._ControlContainer_7_4);
    this._text_8 = this.renderer.createText(this._el_7,'\n    \n    ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_7,'ion-list',(null as any));
    this._List_9_3 = new import18.List(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_9),this.renderer,this.parentInjector.get(import34.GestureController));
    this._text_10 = this.renderer.createText(this._el_9,'\n    \n      ',(null as any));
    this._el_11 = this.renderer.createElement(this._el_9,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_11,'class','textbox-background mob-content-center item item-block');
    this._appEl_11 = new import2.AppElement(11,9,this,this._el_11);
    var compView_11:any = import35.viewFactory_Item0(this.viewUtils,this.injector(11),this._appEl_11);
    this._Item_11_4 = new import19.Item(this.parentInjector.get(import36.Form),this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_11),this.renderer);
    this._ItemContent_11_5 = new import19.ItemContent();
    this._query_Label_11_0 = new import20.QueryList<any>();
    this._query_Button_11_1 = new import20.QueryList<any>();
    this._query_Icon_11_2 = new import20.QueryList<any>();
    this._appEl_11.initComponent(this._Item_11_4,[],compView_11);
    this._text_12 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_13 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_13,'floating','');
    this._Label_13_3 = new import21.Label(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_13),this.renderer,'',(null as any),(null as any),(null as any));
    this._text_14 = this.renderer.createText(this._el_13,'Username',(null as any));
    this._text_15 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_16 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_16,'maxlength','25');
    this.renderer.setElementAttribute(this._el_16,'minlength','5');
    this.renderer.setElementAttribute(this._el_16,'name','username');
    this.renderer.setElementAttribute(this._el_16,'ngModel','');
    this.renderer.setElementAttribute(this._el_16,'required','');
    this.renderer.setElementAttribute(this._el_16,'type','text');
    this._appEl_16 = new import2.AppElement(16,11,this,this._el_16);
    var compView_16:any = import37.viewFactory_TextInput0(this.viewUtils,this.injector(16),this._appEl_16);
    this._RequiredValidator_16_4 = new import22.RequiredValidator();
    this._MinLengthValidator_16_5 = new import22.MinLengthValidator();
    this._MaxLengthValidator_16_6 = new import22.MaxLengthValidator();
    this._NG_VALIDATORS_16_7 = [
      this._RequiredValidator_16_4,
      this._MinLengthValidator_16_5,
      this._MaxLengthValidator_16_6
    ]
    ;
    this._NgModel_16_8 = new import23.NgModel(this._ControlContainer_7_4,this._NG_VALIDATORS_16_7,(null as any),(null as any));
    this._NgControl_16_9 = this._NgModel_16_8;
    this._NgControlStatus_16_10 = new import17.NgControlStatus(this._NgControl_16_9);
    this._TextInput_16_11 = new import24.TextInput(this.parentInjector.get(import27.Config),this.parentInjector.get(import36.Form),this._Item_11_4,this.parentInjector.get(import29.App),this.parentInjector.get(import38.Platform),new import28.ElementRef(this._el_16),this.renderer,this._Content_0_4,this.parentInjector.get(import8.NavController,(null as any)),this._NgControl_16_9);
    this._appEl_16.initComponent(this._TextInput_16_11,[],compView_16);
    this._text_17 = this.renderer.createText((null as any),'\n        ',(null as any));
    compView_16.create(this._TextInput_16_11,[],(null as any));
    this._text_18 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._query_Label_11_0.reset([this._Label_13_3]);
    this._Item_11_4.contentLabel = this._query_Label_11_0.first;
    compView_11.create(this._Item_11_4,[
      [],
      [].concat([this._el_13]),
      [].concat([
        this._text_12,
        this._text_15,
        this._text_18
      ]
      ),
      [].concat([this._el_16]),
      []
    ]
    ,(null as any));
    this._text_19 = this.renderer.createText(this._el_9,'\n      \n      ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_9,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_20,'class','textbox-background mob-content-center item item-block');
    this._appEl_20 = new import2.AppElement(20,9,this,this._el_20);
    var compView_20:any = import35.viewFactory_Item0(this.viewUtils,this.injector(20),this._appEl_20);
    this._Item_20_4 = new import19.Item(this.parentInjector.get(import36.Form),this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_20),this.renderer);
    this._ItemContent_20_5 = new import19.ItemContent();
    this._query_Label_20_0 = new import20.QueryList<any>();
    this._query_Button_20_1 = new import20.QueryList<any>();
    this._query_Icon_20_2 = new import20.QueryList<any>();
    this._appEl_20.initComponent(this._Item_20_4,[],compView_20);
    this._text_21 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_22 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_22,'floating','');
    this._Label_22_3 = new import21.Label(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_22),this.renderer,'',(null as any),(null as any),(null as any));
    this._text_23 = this.renderer.createText(this._el_22,'Password',(null as any));
    this._text_24 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_25 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_25,'maxlength','25');
    this.renderer.setElementAttribute(this._el_25,'minlength','5');
    this.renderer.setElementAttribute(this._el_25,'name','password');
    this.renderer.setElementAttribute(this._el_25,'ngModel','');
    this.renderer.setElementAttribute(this._el_25,'required','');
    this.renderer.setElementAttribute(this._el_25,'type','password');
    this._appEl_25 = new import2.AppElement(25,20,this,this._el_25);
    var compView_25:any = import37.viewFactory_TextInput0(this.viewUtils,this.injector(25),this._appEl_25);
    this._RequiredValidator_25_4 = new import22.RequiredValidator();
    this._MinLengthValidator_25_5 = new import22.MinLengthValidator();
    this._MaxLengthValidator_25_6 = new import22.MaxLengthValidator();
    this._NG_VALIDATORS_25_7 = [
      this._RequiredValidator_25_4,
      this._MinLengthValidator_25_5,
      this._MaxLengthValidator_25_6
    ]
    ;
    this._NgModel_25_8 = new import23.NgModel(this._ControlContainer_7_4,this._NG_VALIDATORS_25_7,(null as any),(null as any));
    this._NgControl_25_9 = this._NgModel_25_8;
    this._NgControlStatus_25_10 = new import17.NgControlStatus(this._NgControl_25_9);
    this._TextInput_25_11 = new import24.TextInput(this.parentInjector.get(import27.Config),this.parentInjector.get(import36.Form),this._Item_20_4,this.parentInjector.get(import29.App),this.parentInjector.get(import38.Platform),new import28.ElementRef(this._el_25),this.renderer,this._Content_0_4,this.parentInjector.get(import8.NavController,(null as any)),this._NgControl_25_9);
    this._appEl_25.initComponent(this._TextInput_25_11,[],compView_25);
    this._text_26 = this.renderer.createText((null as any),'\n        ',(null as any));
    compView_25.create(this._TextInput_25_11,[],(null as any));
    this._text_27 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._query_Label_20_0.reset([this._Label_22_3]);
    this._Item_20_4.contentLabel = this._query_Label_20_0.first;
    compView_20.create(this._Item_20_4,[
      [],
      [].concat([this._el_22]),
      [].concat([
        this._text_21,
        this._text_24,
        this._text_27
      ]
      ),
      [].concat([this._el_25]),
      []
    ]
    ,(null as any));
    this._text_28 = this.renderer.createText(this._el_9,'\n    \n    ',(null as any));
    this._text_29 = this.renderer.createText(this._el_7,'\n      \n     ',(null as any));
    this._el_30 = this.renderer.createElement(this._el_7,'p',(null as any));
    this.renderer.setElementAttribute(this._el_30,'class','align-center');
    this._text_31 = this.renderer.createText(this._el_30,'\n        ',(null as any));
    this._el_32 = this.renderer.createElement(this._el_30,'button',(null as any));
    this.renderer.setElementAttribute(this._el_32,'class','button-background');
    this.renderer.setElementAttribute(this._el_32,'ion-button','');
    this._appEl_32 = new import2.AppElement(32,30,this,this._el_32);
    var compView_32:any = import39.viewFactory_Button0(this.viewUtils,this.injector(32),this._appEl_32);
    this._Button_32_4 = new import25.Button((null as any),'',this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_32),this.renderer);
    this._appEl_32.initComponent(this._Button_32_4,[],compView_32);
    this._text_33 = this.renderer.createText((null as any),'Sign In',(null as any));
    compView_32.create(this._Button_32_4,[[].concat([this._text_33])],(null as any));
    this._text_34 = this.renderer.createText(this._el_30,'\n     ',(null as any));
    this._text_35 = this.renderer.createText(this._el_7,'\n  ',(null as any));
    this._text_36 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_37 = this.renderer.createElement((null as any),'p',(null as any));
    this.renderer.setElementAttribute(this._el_37,'class','text-center mob-flex-center mob-content-center');
    this._text_38 = this.renderer.createText(this._el_37,'\n    ',(null as any));
    this._el_39 = this.renderer.createElement(this._el_37,'a',(null as any));
    this._text_40 = this.renderer.createText(this._el_39,'Not Registered? Sign Up.',(null as any));
    this._text_41 = this.renderer.createText(this._el_37,'\n    ',(null as any));
    this._el_42 = this.renderer.createElement(this._el_37,'button',(null as any));
    this.renderer.setElementAttribute(this._el_42,'class','button forget-password-button');
    this._text_43 = this.renderer.createText(this._el_42,'Forgot Password',(null as any));
    this._text_44 = this.renderer.createText(this._el_37,'\n  ',(null as any));
    this._text_45 = this.renderer.createText((null as any),'\n',(null as any));
    compView_0.create(this._Content_0_4,[
      [],
      [].concat([
        this._text_1,
        this._el_2,
        this._text_6,
        this._el_7,
        this._text_36,
        this._el_37,
        this._text_45
      ]
      ),
      []
    ]
    ,(null as any));
    this._text_46 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_7,'submit',this.eventHandler(this._handle_submit_7_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_7,'reset',this.eventHandler(this._handle_reset_7_1.bind(this)));
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_16,'ngModelChange',this.eventHandler(this._handle_ngModelChange_16_0.bind(this)));
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    this._expr_16 = import7.UNINITIALIZED;
    this._expr_17 = import7.UNINITIALIZED;
    const subscription_0:any = this._NgModel_16_8.update.subscribe(this.eventHandler(this._handle_ngModelChange_16_0.bind(this)));
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_19 = import7.UNINITIALIZED;
    this._expr_20 = import7.UNINITIALIZED;
    this._expr_21 = import7.UNINITIALIZED;
    this._expr_22 = import7.UNINITIALIZED;
    this._expr_23 = import7.UNINITIALIZED;
    this._expr_24 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_25,'ngModelChange',this.eventHandler(this._handle_ngModelChange_25_0.bind(this)));
    this._expr_26 = import7.UNINITIALIZED;
    this._expr_27 = import7.UNINITIALIZED;
    this._expr_28 = import7.UNINITIALIZED;
    this._expr_29 = import7.UNINITIALIZED;
    this._expr_30 = import7.UNINITIALIZED;
    this._expr_31 = import7.UNINITIALIZED;
    this._expr_32 = import7.UNINITIALIZED;
    this._expr_33 = import7.UNINITIALIZED;
    const subscription_1:any = this._NgModel_25_8.update.subscribe(this.eventHandler(this._handle_ngModelChange_25_0.bind(this)));
    this._expr_34 = import7.UNINITIALIZED;
    this._expr_35 = import7.UNINITIALIZED;
    this._expr_36 = import7.UNINITIALIZED;
    this._expr_37 = import7.UNINITIALIZED;
    this._expr_38 = import7.UNINITIALIZED;
    this._expr_39 = import7.UNINITIALIZED;
    this._expr_40 = import7.UNINITIALIZED;
    var disposable_4:Function = this.renderer.listen(this._el_32,'click',this.eventHandler(this._handle_click_32_0.bind(this)));
    var disposable_5:Function = this.renderer.listen(this._el_39,'click',this.eventHandler(this._handle_click_39_0.bind(this)));
    var disposable_6:Function = this.renderer.listen(this._el_42,'click',this.eventHandler(this._handle_click_42_0.bind(this)));
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._text_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._text_34,
      this._text_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._text_44,
      this._text_45,
      this._text_46
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6
    ]
    ,[
      subscription_0,
      subscription_1
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import21.Label) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._Label_13_3; }
    if (((token === import22.RequiredValidator) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._RequiredValidator_16_4; }
    if (((token === import22.MinLengthValidator) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._MinLengthValidator_16_5; }
    if (((token === import22.MaxLengthValidator) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._MaxLengthValidator_16_6; }
    if (((token === import40.NG_VALIDATORS) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._NG_VALIDATORS_16_7; }
    if (((token === import23.NgModel) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._NgModel_16_8; }
    if (((token === import41.NgControl) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._NgControl_16_9; }
    if (((token === import17.NgControlStatus) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._NgControlStatus_16_10; }
    if (((token === import24.TextInput) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._TextInput_16_11; }
    if (((token === import19.Item) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 18)))) { return this._Item_11_4; }
    if (((token === import19.ItemContent) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 18)))) { return this._ItemContent_11_5; }
    if (((token === import21.Label) && ((22 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._Label_22_3; }
    if (((token === import22.RequiredValidator) && ((25 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._RequiredValidator_25_4; }
    if (((token === import22.MinLengthValidator) && ((25 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._MinLengthValidator_25_5; }
    if (((token === import22.MaxLengthValidator) && ((25 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._MaxLengthValidator_25_6; }
    if (((token === import40.NG_VALIDATORS) && ((25 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._NG_VALIDATORS_25_7; }
    if (((token === import23.NgModel) && ((25 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._NgModel_25_8; }
    if (((token === import41.NgControl) && ((25 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._NgControl_25_9; }
    if (((token === import17.NgControlStatus) && ((25 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._NgControlStatus_25_10; }
    if (((token === import24.TextInput) && ((25 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._TextInput_25_11; }
    if (((token === import19.Item) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._Item_20_4; }
    if (((token === import19.ItemContent) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._ItemContent_20_5; }
    if (((token === import18.List) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._List_9_3; }
    if (((token === import25.Button) && ((32 <= requestNodeIndex) && (requestNodeIndex <= 33)))) { return this._Button_32_4; }
    if (((token === import16.NgForm) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._NgForm_7_3; }
    if (((token === import42.ControlContainer) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._ControlContainer_7_4; }
    if (((token === import17.NgControlStatusGroup) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._NgControlStatusGroup_7_5; }
    if (((token === import15.Content) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 45)))) { return this._Content_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_0_4.ngOnInit(); }
    const currVal_10:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this._RequiredValidator_16_4.required = currVal_10;
      this._expr_10 = currVal_10;
    }
    changes = (null as any);
    const currVal_12:any = '5';
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this._MinLengthValidator_16_5.minlength = currVal_12;
      if ((changes === (null as any))) { (changes = {}); }
      changes['minlength'] = new import7.SimpleChange(this._expr_12,currVal_12);
      this._expr_12 = currVal_12;
    }
    if ((changes !== (null as any))) { this._MinLengthValidator_16_5.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_14:any = '25';
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this._MaxLengthValidator_16_6.maxlength = currVal_14;
      if ((changes === (null as any))) { (changes = {}); }
      changes['maxlength'] = new import7.SimpleChange(this._expr_14,currVal_14);
      this._expr_14 = currVal_14;
    }
    if ((changes !== (null as any))) { this._MaxLengthValidator_16_6.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_16:any = 'username';
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this._NgModel_16_8.name = currVal_16;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_16,currVal_16);
      this._expr_16 = currVal_16;
    }
    const currVal_17:any = this.context.username;
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this._NgModel_16_8.model = currVal_17;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_17,currVal_17);
      this._expr_17 = currVal_17;
    }
    if ((changes !== (null as any))) { this._NgModel_16_8.ngOnChanges(changes); }
    const currVal_24:any = 'text';
    if (import4.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this._TextInput_16_11.type = currVal_24;
      this._expr_24 = currVal_24;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._TextInput_16_11.ngOnInit(); }
    const currVal_26:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_26,currVal_26)) {
      this._RequiredValidator_25_4.required = currVal_26;
      this._expr_26 = currVal_26;
    }
    changes = (null as any);
    const currVal_28:any = '5';
    if (import4.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this._MinLengthValidator_25_5.minlength = currVal_28;
      if ((changes === (null as any))) { (changes = {}); }
      changes['minlength'] = new import7.SimpleChange(this._expr_28,currVal_28);
      this._expr_28 = currVal_28;
    }
    if ((changes !== (null as any))) { this._MinLengthValidator_25_5.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_30:any = '25';
    if (import4.checkBinding(throwOnChange,this._expr_30,currVal_30)) {
      this._MaxLengthValidator_25_6.maxlength = currVal_30;
      if ((changes === (null as any))) { (changes = {}); }
      changes['maxlength'] = new import7.SimpleChange(this._expr_30,currVal_30);
      this._expr_30 = currVal_30;
    }
    if ((changes !== (null as any))) { this._MaxLengthValidator_25_6.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_32:any = 'password';
    if (import4.checkBinding(throwOnChange,this._expr_32,currVal_32)) {
      this._NgModel_25_8.name = currVal_32;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_32,currVal_32);
      this._expr_32 = currVal_32;
    }
    const currVal_33:any = this.context.password;
    if (import4.checkBinding(throwOnChange,this._expr_33,currVal_33)) {
      this._NgModel_25_8.model = currVal_33;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_33,currVal_33);
      this._expr_33 = currVal_33;
    }
    if ((changes !== (null as any))) { this._NgModel_25_8.ngOnChanges(changes); }
    const currVal_40:any = 'password';
    if (import4.checkBinding(throwOnChange,this._expr_40,currVal_40)) {
      this._TextInput_25_11.type = currVal_40;
      this._expr_40 = currVal_40;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._TextInput_25_11.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_11_1.dirty) {
        this._query_Button_11_1.reset([]);
        this._Item_11_4._buttons = this._query_Button_11_1;
        this._query_Button_11_1.notifyOnChanges();
      }
      if (this._query_Icon_11_2.dirty) {
        this._query_Icon_11_2.reset([]);
        this._Item_11_4._icons = this._query_Icon_11_2;
        this._query_Icon_11_2.notifyOnChanges();
      }
      if (this._query_Button_20_1.dirty) {
        this._query_Button_20_1.reset([]);
        this._Item_20_4._buttons = this._query_Button_20_1;
        this._query_Button_20_1.notifyOnChanges();
      }
      if (this._query_Icon_20_2.dirty) {
        this._query_Icon_20_2.reset([]);
        this._Item_20_4._icons = this._query_Icon_20_2;
        this._query_Icon_20_2.notifyOnChanges();
      }
      this._TextInput_16_11.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_11_4.ngAfterContentInit(); }
      this._TextInput_25_11.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_20_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_32_4.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Content_0_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementClass(this._el_0,'statusbar-padding',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_3:any = this._NgControlStatusGroup_7_5.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_7,'ng-untouched',currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = this._NgControlStatusGroup_7_5.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_7,'ng-touched',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this._NgControlStatusGroup_7_5.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_7,'ng-pristine',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this._NgControlStatusGroup_7_5.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_7,'ng-dirty',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._NgControlStatusGroup_7_5.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_7,'ng-valid',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatusGroup_7_5.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_7,'ng-invalid',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_11:any = (this._RequiredValidator_16_4.required? '': (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementAttribute(this._el_16,'required',((currVal_11 == (null as any))? (null as any): currVal_11.toString()));
      this._expr_11 = currVal_11;
    }
    const currVal_13:any = (this._MinLengthValidator_16_5.minlength? this._MinLengthValidator_16_5.minlength: (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementAttribute(this._el_16,'minlength',((currVal_13 == (null as any))? (null as any): currVal_13.toString()));
      this._expr_13 = currVal_13;
    }
    const currVal_15:any = (this._MaxLengthValidator_16_6.maxlength? this._MaxLengthValidator_16_6.maxlength: (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementAttribute(this._el_16,'maxlength',((currVal_15 == (null as any))? (null as any): currVal_15.toString()));
      this._expr_15 = currVal_15;
    }
    const currVal_18:any = this._NgControlStatus_16_10.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_16,'ng-untouched',currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = this._NgControlStatus_16_10.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setElementClass(this._el_16,'ng-touched',currVal_19);
      this._expr_19 = currVal_19;
    }
    const currVal_20:any = this._NgControlStatus_16_10.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setElementClass(this._el_16,'ng-pristine',currVal_20);
      this._expr_20 = currVal_20;
    }
    const currVal_21:any = this._NgControlStatus_16_10.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this.renderer.setElementClass(this._el_16,'ng-dirty',currVal_21);
      this._expr_21 = currVal_21;
    }
    const currVal_22:any = this._NgControlStatus_16_10.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this.renderer.setElementClass(this._el_16,'ng-valid',currVal_22);
      this._expr_22 = currVal_22;
    }
    const currVal_23:any = this._NgControlStatus_16_10.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this.renderer.setElementClass(this._el_16,'ng-invalid',currVal_23);
      this._expr_23 = currVal_23;
    }
    const currVal_27:any = (this._RequiredValidator_25_4.required? '': (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this.renderer.setElementAttribute(this._el_25,'required',((currVal_27 == (null as any))? (null as any): currVal_27.toString()));
      this._expr_27 = currVal_27;
    }
    const currVal_29:any = (this._MinLengthValidator_25_5.minlength? this._MinLengthValidator_25_5.minlength: (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this.renderer.setElementAttribute(this._el_25,'minlength',((currVal_29 == (null as any))? (null as any): currVal_29.toString()));
      this._expr_29 = currVal_29;
    }
    const currVal_31:any = (this._MaxLengthValidator_25_6.maxlength? this._MaxLengthValidator_25_6.maxlength: (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_31,currVal_31)) {
      this.renderer.setElementAttribute(this._el_25,'maxlength',((currVal_31 == (null as any))? (null as any): currVal_31.toString()));
      this._expr_31 = currVal_31;
    }
    const currVal_34:any = this._NgControlStatus_25_10.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_34,currVal_34)) {
      this.renderer.setElementClass(this._el_25,'ng-untouched',currVal_34);
      this._expr_34 = currVal_34;
    }
    const currVal_35:any = this._NgControlStatus_25_10.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_35,currVal_35)) {
      this.renderer.setElementClass(this._el_25,'ng-touched',currVal_35);
      this._expr_35 = currVal_35;
    }
    const currVal_36:any = this._NgControlStatus_25_10.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_36,currVal_36)) {
      this.renderer.setElementClass(this._el_25,'ng-pristine',currVal_36);
      this._expr_36 = currVal_36;
    }
    const currVal_37:any = this._NgControlStatus_25_10.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_37,currVal_37)) {
      this.renderer.setElementClass(this._el_25,'ng-dirty',currVal_37);
      this._expr_37 = currVal_37;
    }
    const currVal_38:any = this._NgControlStatus_25_10.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_38,currVal_38)) {
      this.renderer.setElementClass(this._el_25,'ng-valid',currVal_38);
      this._expr_38 = currVal_38;
    }
    const currVal_39:any = this._NgControlStatus_25_10.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_39,currVal_39)) {
      this.renderer.setElementClass(this._el_25,'ng-invalid',currVal_39);
      this._expr_39 = currVal_39;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._NgModel_16_8.ngOnDestroy();
    this._TextInput_16_11.ngOnDestroy();
    this._NgModel_25_8.ngOnDestroy();
    this._TextInput_25_11.ngOnDestroy();
    this._Content_0_4.ngOnDestroy();
  }
  private _handle_submit_7_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_7_3.onSubmit()) !== false);
    return (true && pd_0);
  }
  private _handle_reset_7_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_7_3.onReset()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_16_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.username = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_25_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.password = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_32_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.signIn()) !== false);
    return (true && pd_0);
  }
  private _handle_click_39_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.signUpForm()) !== false);
    return (true && pd_0);
  }
  private _handle_click_42_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.forgotPassword()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_LoginPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.LoginPage> {
  if ((renderType_LoginPage === (null as any))) { (renderType_LoginPage = viewUtils.createRenderComponentType('/Users/mackalvin/Project/Intuitive Surgical/demo/ISI-V2/.tmp/pages/login/login.html',0,import13.ViewEncapsulation.None,styles_LoginPage,{})); }
  return new _View_LoginPage0(viewUtils,parentInjector,declarationEl);
}