/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './login';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from 'ionic-angular/components/alert/alert';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from 'ionic-angular/components/content/content';
import * as import13 from '@angular/forms/src/directives/ng_form';
import * as import14 from '@angular/forms/src/directives/ng_control_status';
import * as import15 from 'ionic-angular/components/list/list';
import * as import16 from 'ionic-angular/components/item/item';
import * as import17 from '@angular/core/src/linker/query_list';
import * as import18 from 'ionic-angular/components/label/label';
import * as import19 from 'ionic-angular/components/input/input';
import * as import20 from 'ionic-angular/components/button/button';
import * as import21 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import22 from 'ionic-angular/config/config';
import * as import23 from '@angular/core/src/linker/element_ref';
import * as import24 from 'ionic-angular/components/app/app';
import * as import25 from 'ionic-angular/util/keyboard';
import * as import26 from '@angular/core/src/zone/ng_zone';
import * as import27 from 'ionic-angular/navigation/view-controller';
import * as import28 from 'ionic-angular/components/tabs/tabs';
import * as import29 from 'ionic-angular/gestures/gesture-controller';
import * as import30 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import31 from 'ionic-angular/util/form';
import * as import32 from '../../node_modules/ionic-angular/components/input/input.ngfactory';
import * as import33 from 'ionic-angular/platform/platform';
import * as import34 from '@angular/forms/src/directives/ng_control';
import * as import35 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import36 from '@angular/forms/src/directives/control_container';
var renderType_LoginPage_Host:import0.RenderComponentType = (null as any);
class _View_LoginPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _LoginPage_0_4:import3.LoginPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_LoginPage_Host0,renderType_LoginPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-login',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_LoginPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._LoginPage_0_4 = new import3.LoginPage(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.AlertController));
    this._appEl_0.initComponent(this._LoginPage_0_4,[],compView_0);
    compView_0.create(this._LoginPage_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.LoginPage) && (0 === requestNodeIndex))) { return this._LoginPage_0_4; }
    return notFoundResult;
  }
}
function viewFactory_LoginPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_LoginPage_Host === (null as any))) { (renderType_LoginPage_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,[],{})); }
  return new _View_LoginPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const LoginPageNgFactory:import11.ComponentFactory<import3.LoginPage> = new import11.ComponentFactory<import3.LoginPage>('page-login',viewFactory_LoginPage_Host0,import3.LoginPage);
const styles_LoginPage:any[] = [];
var renderType_LoginPage:import0.RenderComponentType = (null as any);
class _View_LoginPage0 extends import1.AppView<import3.LoginPage> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _Content_0_4:import12.Content;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _NgForm_7_3:import13.NgForm;
  _ControlContainer_7_4:any;
  _NgControlStatusGroup_7_5:import14.NgControlStatusGroup;
  _text_8:any;
  _el_9:any;
  _List_9_3:import15.List;
  _text_10:any;
  _el_11:any;
  /*private*/ _appEl_11:import2.AppElement;
  _Item_11_4:import16.Item;
  _ItemContent_11_5:import16.ItemContent;
  _query_Label_11_0:import17.QueryList<any>;
  _query_Button_11_1:import17.QueryList<any>;
  _query_Icon_11_2:import17.QueryList<any>;
  _text_12:any;
  _el_13:any;
  _Label_13_3:import18.Label;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  /*private*/ _appEl_16:import2.AppElement;
  _TextInput_16_4:import19.TextInput;
  _text_17:any;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  /*private*/ _appEl_20:import2.AppElement;
  _Item_20_4:import16.Item;
  _ItemContent_20_5:import16.ItemContent;
  _query_Label_20_0:import17.QueryList<any>;
  _query_Button_20_1:import17.QueryList<any>;
  _query_Icon_20_2:import17.QueryList<any>;
  _text_21:any;
  _el_22:any;
  _Label_22_3:import18.Label;
  _text_23:any;
  _text_24:any;
  _el_25:any;
  /*private*/ _appEl_25:import2.AppElement;
  _TextInput_25_4:import19.TextInput;
  _text_26:any;
  _text_27:any;
  _text_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _el_32:any;
  /*private*/ _appEl_32:import2.AppElement;
  _Button_32_4:import20.Button;
  _text_33:any;
  _text_34:any;
  _text_35:any;
  _text_36:any;
  _el_37:any;
  _text_38:any;
  _el_39:any;
  _text_40:any;
  _text_41:any;
  _el_42:any;
  _text_43:any;
  _text_44:any;
  _text_45:any;
  _text_46:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_LoginPage0,renderType_LoginPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','padding page-parent');
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import21.viewFactory_Content0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Content_0_4 = new import12.Content(this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import24.App),this.parentInjector.get(import25.Keyboard),this.parentInjector.get(import26.NgZone),this.parentInjector.get(import27.ViewController,(null as any)),this.parentInjector.get(import28.Tabs,(null as any)));
    this._appEl_0.initComponent(this._Content_0_4,[],compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'img',(null as any));
    this.renderer.setElementAttribute(this._el_4,'src','assets/img/isi_logo.png');
    this._text_5 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_7 = this.renderer.createElement((null as any),'form',(null as any));
    this.renderer.setElementAttribute(this._el_7,'name','signinForm');
    this.renderer.setElementAttribute(this._el_7,'ng-submit','view.signIn(signinForm)');
    this.renderer.setElementAttribute(this._el_7,'novalidate','');
    this._NgForm_7_3 = new import13.NgForm((null as any),(null as any));
    this._ControlContainer_7_4 = this._NgForm_7_3;
    this._NgControlStatusGroup_7_5 = new import14.NgControlStatusGroup(this._ControlContainer_7_4);
    this._text_8 = this.renderer.createText(this._el_7,'\n    \n    ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_7,'ion-list',(null as any));
    this._List_9_3 = new import15.List(this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_9),this.renderer,this.parentInjector.get(import29.GestureController));
    this._text_10 = this.renderer.createText(this._el_9,'\n    \n      ',(null as any));
    this._el_11 = this.renderer.createElement(this._el_9,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_11,'class','textbox-background mob-content-center item item-block');
    this._appEl_11 = new import2.AppElement(11,9,this,this._el_11);
    var compView_11:any = import30.viewFactory_Item0(this.viewUtils,this.injector(11),this._appEl_11);
    this._Item_11_4 = new import16.Item(this.parentInjector.get(import31.Form),this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_11),this.renderer);
    this._ItemContent_11_5 = new import16.ItemContent();
    this._query_Label_11_0 = new import17.QueryList<any>();
    this._query_Button_11_1 = new import17.QueryList<any>();
    this._query_Icon_11_2 = new import17.QueryList<any>();
    this._appEl_11.initComponent(this._Item_11_4,[],compView_11);
    this._text_12 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_13 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_13,'floating','');
    this._Label_13_3 = new import18.Label(this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_13),this.renderer,'',(null as any),(null as any),(null as any));
    this._text_14 = this.renderer.createText(this._el_13,'Username',(null as any));
    this._text_15 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_16 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_16,'name','username');
    this.renderer.setElementAttribute(this._el_16,'ng-maxlength','25');
    this.renderer.setElementAttribute(this._el_16,'ng-minlength','5');
    this.renderer.setElementAttribute(this._el_16,'ng-model','view.username');
    this.renderer.setElementAttribute(this._el_16,'required','');
    this.renderer.setElementAttribute(this._el_16,'type','text');
    this._appEl_16 = new import2.AppElement(16,11,this,this._el_16);
    var compView_16:any = import32.viewFactory_TextInput0(this.viewUtils,this.injector(16),this._appEl_16);
    this._TextInput_16_4 = new import19.TextInput(this.parentInjector.get(import22.Config),this.parentInjector.get(import31.Form),this._Item_11_4,this.parentInjector.get(import24.App),this.parentInjector.get(import33.Platform),new import23.ElementRef(this._el_16),this.renderer,this._Content_0_4,this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import34.NgControl,(null as any)));
    this._appEl_16.initComponent(this._TextInput_16_4,[],compView_16);
    this._text_17 = this.renderer.createText((null as any),'\n        ',(null as any));
    compView_16.create(this._TextInput_16_4,[],(null as any));
    this._text_18 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._query_Label_11_0.reset([this._Label_13_3]);
    this._Item_11_4.contentLabel = this._query_Label_11_0.first;
    compView_11.create(this._Item_11_4,[
      [],
      [].concat([this._el_13]),
      [].concat([
        this._text_12,
        this._text_15,
        this._text_18
      ]
      ),
      [].concat([this._el_16]),
      []
    ]
    ,(null as any));
    this._text_19 = this.renderer.createText(this._el_9,'\n      \n      ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_9,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_20,'class','textbox-background mob-content-center item item-block');
    this._appEl_20 = new import2.AppElement(20,9,this,this._el_20);
    var compView_20:any = import30.viewFactory_Item0(this.viewUtils,this.injector(20),this._appEl_20);
    this._Item_20_4 = new import16.Item(this.parentInjector.get(import31.Form),this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_20),this.renderer);
    this._ItemContent_20_5 = new import16.ItemContent();
    this._query_Label_20_0 = new import17.QueryList<any>();
    this._query_Button_20_1 = new import17.QueryList<any>();
    this._query_Icon_20_2 = new import17.QueryList<any>();
    this._appEl_20.initComponent(this._Item_20_4,[],compView_20);
    this._text_21 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_22 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_22,'floating','');
    this._Label_22_3 = new import18.Label(this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_22),this.renderer,'',(null as any),(null as any),(null as any));
    this._text_23 = this.renderer.createText(this._el_22,'Password',(null as any));
    this._text_24 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_25 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_25,'name','password');
    this.renderer.setElementAttribute(this._el_25,'ng-maxlength','25');
    this.renderer.setElementAttribute(this._el_25,'ng-minlength','5');
    this.renderer.setElementAttribute(this._el_25,'ng-model','view.password');
    this.renderer.setElementAttribute(this._el_25,'required','');
    this.renderer.setElementAttribute(this._el_25,'type','password');
    this._appEl_25 = new import2.AppElement(25,20,this,this._el_25);
    var compView_25:any = import32.viewFactory_TextInput0(this.viewUtils,this.injector(25),this._appEl_25);
    this._TextInput_25_4 = new import19.TextInput(this.parentInjector.get(import22.Config),this.parentInjector.get(import31.Form),this._Item_20_4,this.parentInjector.get(import24.App),this.parentInjector.get(import33.Platform),new import23.ElementRef(this._el_25),this.renderer,this._Content_0_4,this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import34.NgControl,(null as any)));
    this._appEl_25.initComponent(this._TextInput_25_4,[],compView_25);
    this._text_26 = this.renderer.createText((null as any),'\n        ',(null as any));
    compView_25.create(this._TextInput_25_4,[],(null as any));
    this._text_27 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._query_Label_20_0.reset([this._Label_22_3]);
    this._Item_20_4.contentLabel = this._query_Label_20_0.first;
    compView_20.create(this._Item_20_4,[
      [],
      [].concat([this._el_22]),
      [].concat([
        this._text_21,
        this._text_24,
        this._text_27
      ]
      ),
      [].concat([this._el_25]),
      []
    ]
    ,(null as any));
    this._text_28 = this.renderer.createText(this._el_9,'\n    \n    ',(null as any));
    this._text_29 = this.renderer.createText(this._el_7,'\n      \n     ',(null as any));
    this._el_30 = this.renderer.createElement(this._el_7,'p',(null as any));
    this.renderer.setElementAttribute(this._el_30,'class','align-center');
    this._text_31 = this.renderer.createText(this._el_30,'\n        ',(null as any));
    this._el_32 = this.renderer.createElement(this._el_30,'button',(null as any));
    this.renderer.setElementAttribute(this._el_32,'class','button-background');
    this.renderer.setElementAttribute(this._el_32,'ion-button','');
    this._appEl_32 = new import2.AppElement(32,30,this,this._el_32);
    var compView_32:any = import35.viewFactory_Button0(this.viewUtils,this.injector(32),this._appEl_32);
    this._Button_32_4 = new import20.Button((null as any),'',this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_32),this.renderer);
    this._appEl_32.initComponent(this._Button_32_4,[],compView_32);
    this._text_33 = this.renderer.createText((null as any),'Sign In',(null as any));
    compView_32.create(this._Button_32_4,[[].concat([this._text_33])],(null as any));
    this._text_34 = this.renderer.createText(this._el_30,'\n     ',(null as any));
    this._text_35 = this.renderer.createText(this._el_7,'\n  ',(null as any));
    this._text_36 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_37 = this.renderer.createElement((null as any),'p',(null as any));
    this.renderer.setElementAttribute(this._el_37,'class','text-center mob-flex-center mob-content-center');
    this._text_38 = this.renderer.createText(this._el_37,'\n    ',(null as any));
    this._el_39 = this.renderer.createElement(this._el_37,'a',(null as any));
    this._text_40 = this.renderer.createText(this._el_39,'Not Registered? Sign Up.',(null as any));
    this._text_41 = this.renderer.createText(this._el_37,'\n    ',(null as any));
    this._el_42 = this.renderer.createElement(this._el_37,'button',(null as any));
    this.renderer.setElementAttribute(this._el_42,'class','button forget-password-button');
    this._text_43 = this.renderer.createText(this._el_42,'Forgot Password',(null as any));
    this._text_44 = this.renderer.createText(this._el_37,'\n  ',(null as any));
    this._text_45 = this.renderer.createText((null as any),'\n',(null as any));
    compView_0.create(this._Content_0_4,[
      [],
      [].concat([
        this._text_1,
        this._el_2,
        this._text_6,
        this._el_7,
        this._text_36,
        this._el_37,
        this._text_45
      ]
      ),
      []
    ]
    ,(null as any));
    this._text_46 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_7,'submit',this.eventHandler(this._handle_submit_7_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_7,'reset',this.eventHandler(this._handle_reset_7_1.bind(this)));
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_39,'click',this.eventHandler(this._handle_click_39_0.bind(this)));
    var disposable_3:Function = this.renderer.listen(this._el_42,'click',this.eventHandler(this._handle_click_42_0.bind(this)));
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._text_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._text_34,
      this._text_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._text_44,
      this._text_45,
      this._text_46
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import18.Label) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._Label_13_3; }
    if (((token === import19.TextInput) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._TextInput_16_4; }
    if (((token === import16.Item) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 18)))) { return this._Item_11_4; }
    if (((token === import16.ItemContent) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 18)))) { return this._ItemContent_11_5; }
    if (((token === import18.Label) && ((22 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._Label_22_3; }
    if (((token === import19.TextInput) && ((25 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._TextInput_25_4; }
    if (((token === import16.Item) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._Item_20_4; }
    if (((token === import16.ItemContent) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._ItemContent_20_5; }
    if (((token === import15.List) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._List_9_3; }
    if (((token === import20.Button) && ((32 <= requestNodeIndex) && (requestNodeIndex <= 33)))) { return this._Button_32_4; }
    if (((token === import13.NgForm) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._NgForm_7_3; }
    if (((token === import36.ControlContainer) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._ControlContainer_7_4; }
    if (((token === import14.NgControlStatusGroup) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._NgControlStatusGroup_7_5; }
    if (((token === import12.Content) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 45)))) { return this._Content_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_0_4.ngOnInit(); }
    const currVal_9:any = 'text';
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this._TextInput_16_4.type = currVal_9;
      this._expr_9 = currVal_9;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._TextInput_16_4.ngOnInit(); }
    const currVal_10:any = 'password';
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this._TextInput_25_4.type = currVal_10;
      this._expr_10 = currVal_10;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._TextInput_25_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_11_1.dirty) {
        this._query_Button_11_1.reset([]);
        this._Item_11_4._buttons = this._query_Button_11_1;
        this._query_Button_11_1.notifyOnChanges();
      }
      if (this._query_Icon_11_2.dirty) {
        this._query_Icon_11_2.reset([]);
        this._Item_11_4._icons = this._query_Icon_11_2;
        this._query_Icon_11_2.notifyOnChanges();
      }
      if (this._query_Button_20_1.dirty) {
        this._query_Button_20_1.reset([]);
        this._Item_20_4._buttons = this._query_Button_20_1;
        this._query_Button_20_1.notifyOnChanges();
      }
      if (this._query_Icon_20_2.dirty) {
        this._query_Icon_20_2.reset([]);
        this._Item_20_4._icons = this._query_Icon_20_2;
        this._query_Icon_20_2.notifyOnChanges();
      }
      this._TextInput_16_4.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_11_4.ngAfterContentInit(); }
      this._TextInput_25_4.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_20_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_32_4.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Content_0_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementClass(this._el_0,'statusbar-padding',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_3:any = this._NgControlStatusGroup_7_5.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_7,'ng-untouched',currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = this._NgControlStatusGroup_7_5.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_7,'ng-touched',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this._NgControlStatusGroup_7_5.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_7,'ng-pristine',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this._NgControlStatusGroup_7_5.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_7,'ng-dirty',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._NgControlStatusGroup_7_5.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_7,'ng-valid',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatusGroup_7_5.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_7,'ng-invalid',currVal_8);
      this._expr_8 = currVal_8;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._TextInput_16_4.ngOnDestroy();
    this._TextInput_25_4.ngOnDestroy();
    this._Content_0_4.ngOnDestroy();
  }
  private _handle_submit_7_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_7_3.onSubmit()) !== false);
    return (true && pd_0);
  }
  private _handle_reset_7_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_7_3.onReset()) !== false);
    return (true && pd_0);
  }
  private _handle_click_39_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.signUp()) !== false);
    return (true && pd_0);
  }
  private _handle_click_42_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.forgotPassword()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_LoginPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.LoginPage> {
  if ((renderType_LoginPage === (null as any))) { (renderType_LoginPage = viewUtils.createRenderComponentType('/Users/mackalvin/Downloads/ISI-V2/.tmp/pages/login/login.html',0,import10.ViewEncapsulation.None,styles_LoginPage,{})); }
  return new _View_LoginPage0(viewUtils,parentInjector,declarationEl);
}