/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './registration';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from 'ionic-angular/components/toolbar/toolbar';
import * as import12 from 'ionic-angular/components/navbar/navbar';
import * as import13 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import14 from 'ionic-angular/components/content/content';
import * as import15 from '@angular/forms/src/directives/ng_form';
import * as import16 from '@angular/forms/src/directives/ng_control_status';
import * as import17 from 'ionic-angular/components/list/list';
import * as import18 from 'ionic-angular/components/item/item';
import * as import19 from '@angular/core/src/linker/query_list';
import * as import20 from 'ionic-angular/components/label/label';
import * as import21 from 'ionic-angular/components/input/input';
import * as import22 from 'ionic-angular/components/button/button';
import * as import23 from 'ionic-angular/config/config';
import * as import24 from '@angular/core/src/linker/element_ref';
import * as import25 from 'ionic-angular/navigation/view-controller';
import * as import26 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import27 from 'ionic-angular/components/app/app';
import * as import28 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import29 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import30 from 'ionic-angular/util/keyboard';
import * as import31 from '@angular/core/src/zone/ng_zone';
import * as import32 from 'ionic-angular/components/tabs/tabs';
import * as import33 from 'ionic-angular/gestures/gesture-controller';
import * as import34 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import35 from 'ionic-angular/util/form';
import * as import36 from '../../node_modules/ionic-angular/components/input/input.ngfactory';
import * as import37 from 'ionic-angular/platform/platform';
import * as import38 from '@angular/forms/src/directives/ng_control';
import * as import39 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import40 from '@angular/forms/src/directives/control_container';
var renderType_RegistrationPage_Host:import0.RenderComponentType = (null as any);
class _View_RegistrationPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _RegistrationPage_0_4:import3.RegistrationPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_RegistrationPage_Host0,renderType_RegistrationPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-registration',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_RegistrationPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._RegistrationPage_0_4 = new import3.RegistrationPage(this.parentInjector.get(import8.NavController));
    this._appEl_0.initComponent(this._RegistrationPage_0_4,[],compView_0);
    compView_0.create(this._RegistrationPage_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.RegistrationPage) && (0 === requestNodeIndex))) { return this._RegistrationPage_0_4; }
    return notFoundResult;
  }
}
function viewFactory_RegistrationPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_RegistrationPage_Host === (null as any))) { (renderType_RegistrationPage_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,[],{})); }
  return new _View_RegistrationPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const RegistrationPageNgFactory:import10.ComponentFactory<import3.RegistrationPage> = new import10.ComponentFactory<import3.RegistrationPage>('page-registration',viewFactory_RegistrationPage_Host0,import3.RegistrationPage);
const styles_RegistrationPage:any[] = [];
var renderType_RegistrationPage:import0.RenderComponentType = (null as any);
class _View_RegistrationPage0 extends import1.AppView<import3.RegistrationPage> {
  _el_0:any;
  _Header_0_3:import11.Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Navbar_2_4:import12.Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _ToolbarTitle_4_4:import13.ToolbarTitle;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import2.AppElement;
  _Content_9_4:import14.Content;
  _text_10:any;
  _el_11:any;
  _NgForm_11_3:import15.NgForm;
  _ControlContainer_11_4:any;
  _NgControlStatusGroup_11_5:import16.NgControlStatusGroup;
  _text_12:any;
  _el_13:any;
  _List_13_3:import17.List;
  _text_14:any;
  _el_15:any;
  /*private*/ _appEl_15:import2.AppElement;
  _Item_15_4:import18.Item;
  _ItemContent_15_5:import18.ItemContent;
  _query_Label_15_0:import19.QueryList<any>;
  _query_Button_15_1:import19.QueryList<any>;
  _query_Icon_15_2:import19.QueryList<any>;
  _text_16:any;
  _el_17:any;
  _Label_17_3:import20.Label;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  /*private*/ _appEl_20:import2.AppElement;
  _TextInput_20_4:import21.TextInput;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  /*private*/ _appEl_24:import2.AppElement;
  _Item_24_4:import18.Item;
  _ItemContent_24_5:import18.ItemContent;
  _query_Label_24_0:import19.QueryList<any>;
  _query_Button_24_1:import19.QueryList<any>;
  _query_Icon_24_2:import19.QueryList<any>;
  _text_25:any;
  _el_26:any;
  _Label_26_3:import20.Label;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  /*private*/ _appEl_29:import2.AppElement;
  _TextInput_29_4:import21.TextInput;
  _text_30:any;
  _text_31:any;
  _text_32:any;
  _el_33:any;
  /*private*/ _appEl_33:import2.AppElement;
  _Item_33_4:import18.Item;
  _ItemContent_33_5:import18.ItemContent;
  _query_Label_33_0:import19.QueryList<any>;
  _query_Button_33_1:import19.QueryList<any>;
  _query_Icon_33_2:import19.QueryList<any>;
  _text_34:any;
  _el_35:any;
  _Label_35_3:import20.Label;
  _text_36:any;
  _text_37:any;
  _el_38:any;
  /*private*/ _appEl_38:import2.AppElement;
  _TextInput_38_4:import21.TextInput;
  _text_39:any;
  _text_40:any;
  _text_41:any;
  _el_42:any;
  /*private*/ _appEl_42:import2.AppElement;
  _Item_42_4:import18.Item;
  _ItemContent_42_5:import18.ItemContent;
  _query_Label_42_0:import19.QueryList<any>;
  _query_Button_42_1:import19.QueryList<any>;
  _query_Icon_42_2:import19.QueryList<any>;
  _text_43:any;
  _el_44:any;
  _Label_44_3:import20.Label;
  _text_45:any;
  _text_46:any;
  _el_47:any;
  /*private*/ _appEl_47:import2.AppElement;
  _TextInput_47_4:import21.TextInput;
  _text_48:any;
  _text_49:any;
  _text_50:any;
  _el_51:any;
  /*private*/ _appEl_51:import2.AppElement;
  _Item_51_4:import18.Item;
  _ItemContent_51_5:import18.ItemContent;
  _query_Label_51_0:import19.QueryList<any>;
  _query_Button_51_1:import19.QueryList<any>;
  _query_Icon_51_2:import19.QueryList<any>;
  _text_52:any;
  _el_53:any;
  _Label_53_3:import20.Label;
  _text_54:any;
  _text_55:any;
  _el_56:any;
  /*private*/ _appEl_56:import2.AppElement;
  _TextInput_56_4:import21.TextInput;
  _text_57:any;
  _text_58:any;
  _text_59:any;
  _el_60:any;
  /*private*/ _appEl_60:import2.AppElement;
  _Item_60_4:import18.Item;
  _ItemContent_60_5:import18.ItemContent;
  _query_Label_60_0:import19.QueryList<any>;
  _query_Button_60_1:import19.QueryList<any>;
  _query_Icon_60_2:import19.QueryList<any>;
  _text_61:any;
  _el_62:any;
  _Label_62_3:import20.Label;
  _text_63:any;
  _text_64:any;
  _el_65:any;
  /*private*/ _appEl_65:import2.AppElement;
  _TextInput_65_4:import21.TextInput;
  _text_66:any;
  _text_67:any;
  _text_68:any;
  _text_69:any;
  _text_70:any;
  _el_71:any;
  _text_72:any;
  _el_73:any;
  /*private*/ _appEl_73:import2.AppElement;
  _Button_73_4:import22.Button;
  _text_74:any;
  _text_75:any;
  _text_76:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_RegistrationPage0,renderType_RegistrationPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import11.Header(this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import25.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import26.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import12.Navbar(this.parentInjector.get(import27.App),this.parentInjector.get(import25.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4,[],compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_4 = new import2.AppElement(4,2,this,this._el_4);
    var compView_4:any = import28.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(4),this._appEl_4);
    this._ToolbarTitle_4_4 = new import13.ToolbarTitle(this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import11.Toolbar,(null as any)),this._Navbar_2_4);
    this._appEl_4.initComponent(this._ToolbarTitle_4_4,[],compView_4);
    this._text_5 = this.renderer.createText((null as any),'Sign Up',(null as any));
    compView_4.create(this._ToolbarTitle_4_4,[[].concat([this._text_5])],(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n    ',(null as any));
    compView_2.create(this._Navbar_2_4,[
      [],
      [],
      [],
      [].concat([
        this._text_3,
        this._el_4,
        this._text_6
      ]
      )
    ]
    ,(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_8 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_9 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_9,'class','padding page-parent');
    this._appEl_9 = new import2.AppElement(9,(null as any),this,this._el_9);
    var compView_9:any = import29.viewFactory_Content0(this.viewUtils,this.injector(9),this._appEl_9);
    this._Content_9_4 = new import14.Content(this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_9),this.renderer,this.parentInjector.get(import27.App),this.parentInjector.get(import30.Keyboard),this.parentInjector.get(import31.NgZone),this.parentInjector.get(import25.ViewController,(null as any)),this.parentInjector.get(import32.Tabs,(null as any)));
    this._appEl_9.initComponent(this._Content_9_4,[],compView_9);
    this._text_10 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_11 = this.renderer.createElement((null as any),'form',(null as any));
    this.renderer.setElementAttribute(this._el_11,'class','form');
    this.renderer.setElementAttribute(this._el_11,'id','nameform');
    this.renderer.setElementAttribute(this._el_11,'name','view.registrationForm');
    this.renderer.setElementAttribute(this._el_11,'novalidate','');
    this._NgForm_11_3 = new import15.NgForm((null as any),(null as any));
    this._ControlContainer_11_4 = this._NgForm_11_3;
    this._NgControlStatusGroup_11_5 = new import16.NgControlStatusGroup(this._ControlContainer_11_4);
    this._text_12 = this.renderer.createText(this._el_11,'\n        \n        ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_11,'ion-list',(null as any));
    this._List_13_3 = new import17.List(this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_13),this.renderer,this.parentInjector.get(import33.GestureController));
    this._text_14 = this.renderer.createText(this._el_13,'\n\n            ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_13,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_15,'class','textbox-background mob-content-center item item-block');
    this._appEl_15 = new import2.AppElement(15,13,this,this._el_15);
    var compView_15:any = import34.viewFactory_Item0(this.viewUtils,this.injector(15),this._appEl_15);
    this._Item_15_4 = new import18.Item(this.parentInjector.get(import35.Form),this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_15),this.renderer);
    this._ItemContent_15_5 = new import18.ItemContent();
    this._query_Label_15_0 = new import19.QueryList<any>();
    this._query_Button_15_1 = new import19.QueryList<any>();
    this._query_Icon_15_2 = new import19.QueryList<any>();
    this._appEl_15.initComponent(this._Item_15_4,[],compView_15);
    this._text_16 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_17 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_17,'floating','');
    this._Label_17_3 = new import20.Label(this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_17),this.renderer,'',(null as any),(null as any),(null as any));
    this._text_18 = this.renderer.createText(this._el_17,'FirstName',(null as any));
    this._text_19 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_20 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_20,'name','firstname');
    this.renderer.setElementAttribute(this._el_20,'ng-maxlength','25');
    this.renderer.setElementAttribute(this._el_20,'ng-model','view.firstname');
    this.renderer.setElementAttribute(this._el_20,'required','');
    this.renderer.setElementAttribute(this._el_20,'type','text');
    this._appEl_20 = new import2.AppElement(20,15,this,this._el_20);
    var compView_20:any = import36.viewFactory_TextInput0(this.viewUtils,this.injector(20),this._appEl_20);
    this._TextInput_20_4 = new import21.TextInput(this.parentInjector.get(import23.Config),this.parentInjector.get(import35.Form),this._Item_15_4,this.parentInjector.get(import27.App),this.parentInjector.get(import37.Platform),new import24.ElementRef(this._el_20),this.renderer,this._Content_9_4,this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import38.NgControl,(null as any)));
    this._appEl_20.initComponent(this._TextInput_20_4,[],compView_20);
    this._text_21 = this.renderer.createText((null as any),'\n                ',(null as any));
    compView_20.create(this._TextInput_20_4,[],(null as any));
    this._text_22 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._query_Label_15_0.reset([this._Label_17_3]);
    this._Item_15_4.contentLabel = this._query_Label_15_0.first;
    compView_15.create(this._Item_15_4,[
      [],
      [].concat([this._el_17]),
      [].concat([
        this._text_16,
        this._text_19,
        this._text_22
      ]
      ),
      [].concat([this._el_20]),
      []
    ]
    ,(null as any));
    this._text_23 = this.renderer.createText(this._el_13,'\n            \n            ',(null as any));
    this._el_24 = this.renderer.createElement(this._el_13,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_24,'class','textbox-background mob-content-center item item-block');
    this._appEl_24 = new import2.AppElement(24,13,this,this._el_24);
    var compView_24:any = import34.viewFactory_Item0(this.viewUtils,this.injector(24),this._appEl_24);
    this._Item_24_4 = new import18.Item(this.parentInjector.get(import35.Form),this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_24),this.renderer);
    this._ItemContent_24_5 = new import18.ItemContent();
    this._query_Label_24_0 = new import19.QueryList<any>();
    this._query_Button_24_1 = new import19.QueryList<any>();
    this._query_Icon_24_2 = new import19.QueryList<any>();
    this._appEl_24.initComponent(this._Item_24_4,[],compView_24);
    this._text_25 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_26 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_26,'floating','');
    this._Label_26_3 = new import20.Label(this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_26),this.renderer,'',(null as any),(null as any),(null as any));
    this._text_27 = this.renderer.createText(this._el_26,'LastName',(null as any));
    this._text_28 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_29 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_29,'name','lastname');
    this.renderer.setElementAttribute(this._el_29,'ng-maxlength','25');
    this.renderer.setElementAttribute(this._el_29,'ng-model','view.lastname');
    this.renderer.setElementAttribute(this._el_29,'required','');
    this.renderer.setElementAttribute(this._el_29,'type','text');
    this._appEl_29 = new import2.AppElement(29,24,this,this._el_29);
    var compView_29:any = import36.viewFactory_TextInput0(this.viewUtils,this.injector(29),this._appEl_29);
    this._TextInput_29_4 = new import21.TextInput(this.parentInjector.get(import23.Config),this.parentInjector.get(import35.Form),this._Item_24_4,this.parentInjector.get(import27.App),this.parentInjector.get(import37.Platform),new import24.ElementRef(this._el_29),this.renderer,this._Content_9_4,this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import38.NgControl,(null as any)));
    this._appEl_29.initComponent(this._TextInput_29_4,[],compView_29);
    this._text_30 = this.renderer.createText((null as any),'\n                ',(null as any));
    compView_29.create(this._TextInput_29_4,[],(null as any));
    this._text_31 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._query_Label_24_0.reset([this._Label_26_3]);
    this._Item_24_4.contentLabel = this._query_Label_24_0.first;
    compView_24.create(this._Item_24_4,[
      [],
      [].concat([this._el_26]),
      [].concat([
        this._text_25,
        this._text_28,
        this._text_31
      ]
      ),
      [].concat([this._el_29]),
      []
    ]
    ,(null as any));
    this._text_32 = this.renderer.createText(this._el_13,'\n            \n            ',(null as any));
    this._el_33 = this.renderer.createElement(this._el_13,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_33,'class','textbox-background mob-content-center item item-block');
    this._appEl_33 = new import2.AppElement(33,13,this,this._el_33);
    var compView_33:any = import34.viewFactory_Item0(this.viewUtils,this.injector(33),this._appEl_33);
    this._Item_33_4 = new import18.Item(this.parentInjector.get(import35.Form),this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_33),this.renderer);
    this._ItemContent_33_5 = new import18.ItemContent();
    this._query_Label_33_0 = new import19.QueryList<any>();
    this._query_Button_33_1 = new import19.QueryList<any>();
    this._query_Icon_33_2 = new import19.QueryList<any>();
    this._appEl_33.initComponent(this._Item_33_4,[],compView_33);
    this._text_34 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_35 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_35,'floating','');
    this._Label_35_3 = new import20.Label(this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_35),this.renderer,'',(null as any),(null as any),(null as any));
    this._text_36 = this.renderer.createText(this._el_35,'Email',(null as any));
    this._text_37 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_38 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_38,'name','email');
    this.renderer.setElementAttribute(this._el_38,'ng-change','view.onChange(\'email\')');
    this.renderer.setElementAttribute(this._el_38,'ng-maxlength','25');
    this.renderer.setElementAttribute(this._el_38,'ng-model','view.email');
    this.renderer.setElementAttribute(this._el_38,'required','');
    this.renderer.setElementAttribute(this._el_38,'type','text');
    this._appEl_38 = new import2.AppElement(38,33,this,this._el_38);
    var compView_38:any = import36.viewFactory_TextInput0(this.viewUtils,this.injector(38),this._appEl_38);
    this._TextInput_38_4 = new import21.TextInput(this.parentInjector.get(import23.Config),this.parentInjector.get(import35.Form),this._Item_33_4,this.parentInjector.get(import27.App),this.parentInjector.get(import37.Platform),new import24.ElementRef(this._el_38),this.renderer,this._Content_9_4,this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import38.NgControl,(null as any)));
    this._appEl_38.initComponent(this._TextInput_38_4,[],compView_38);
    this._text_39 = this.renderer.createText((null as any),'\n                ',(null as any));
    compView_38.create(this._TextInput_38_4,[],(null as any));
    this._text_40 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._query_Label_33_0.reset([this._Label_35_3]);
    this._Item_33_4.contentLabel = this._query_Label_33_0.first;
    compView_33.create(this._Item_33_4,[
      [],
      [].concat([this._el_35]),
      [].concat([
        this._text_34,
        this._text_37,
        this._text_40
      ]
      ),
      [].concat([this._el_38]),
      []
    ]
    ,(null as any));
    this._text_41 = this.renderer.createText(this._el_13,'\n            \n            ',(null as any));
    this._el_42 = this.renderer.createElement(this._el_13,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_42,'class','textbox-background mob-content-center item item-block');
    this._appEl_42 = new import2.AppElement(42,13,this,this._el_42);
    var compView_42:any = import34.viewFactory_Item0(this.viewUtils,this.injector(42),this._appEl_42);
    this._Item_42_4 = new import18.Item(this.parentInjector.get(import35.Form),this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_42),this.renderer);
    this._ItemContent_42_5 = new import18.ItemContent();
    this._query_Label_42_0 = new import19.QueryList<any>();
    this._query_Button_42_1 = new import19.QueryList<any>();
    this._query_Icon_42_2 = new import19.QueryList<any>();
    this._appEl_42.initComponent(this._Item_42_4,[],compView_42);
    this._text_43 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_44 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_44,'floating','');
    this._Label_44_3 = new import20.Label(this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_44),this.renderer,'',(null as any),(null as any),(null as any));
    this._text_45 = this.renderer.createText(this._el_44,'Password',(null as any));
    this._text_46 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_47 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_47,'name','password');
    this.renderer.setElementAttribute(this._el_47,'ng-maxlength','25');
    this.renderer.setElementAttribute(this._el_47,'ng-minlength','5');
    this.renderer.setElementAttribute(this._el_47,'ng-model','view.password');
    this.renderer.setElementAttribute(this._el_47,'required','');
    this.renderer.setElementAttribute(this._el_47,'type','password');
    this._appEl_47 = new import2.AppElement(47,42,this,this._el_47);
    var compView_47:any = import36.viewFactory_TextInput0(this.viewUtils,this.injector(47),this._appEl_47);
    this._TextInput_47_4 = new import21.TextInput(this.parentInjector.get(import23.Config),this.parentInjector.get(import35.Form),this._Item_42_4,this.parentInjector.get(import27.App),this.parentInjector.get(import37.Platform),new import24.ElementRef(this._el_47),this.renderer,this._Content_9_4,this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import38.NgControl,(null as any)));
    this._appEl_47.initComponent(this._TextInput_47_4,[],compView_47);
    this._text_48 = this.renderer.createText((null as any),'\n                ',(null as any));
    compView_47.create(this._TextInput_47_4,[],(null as any));
    this._text_49 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._query_Label_42_0.reset([this._Label_44_3]);
    this._Item_42_4.contentLabel = this._query_Label_42_0.first;
    compView_42.create(this._Item_42_4,[
      [],
      [].concat([this._el_44]),
      [].concat([
        this._text_43,
        this._text_46,
        this._text_49
      ]
      ),
      [].concat([this._el_47]),
      []
    ]
    ,(null as any));
    this._text_50 = this.renderer.createText(this._el_13,'\n            \n            ',(null as any));
    this._el_51 = this.renderer.createElement(this._el_13,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_51,'class','textbox-background mob-content-center item item-block');
    this._appEl_51 = new import2.AppElement(51,13,this,this._el_51);
    var compView_51:any = import34.viewFactory_Item0(this.viewUtils,this.injector(51),this._appEl_51);
    this._Item_51_4 = new import18.Item(this.parentInjector.get(import35.Form),this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_51),this.renderer);
    this._ItemContent_51_5 = new import18.ItemContent();
    this._query_Label_51_0 = new import19.QueryList<any>();
    this._query_Button_51_1 = new import19.QueryList<any>();
    this._query_Icon_51_2 = new import19.QueryList<any>();
    this._appEl_51.initComponent(this._Item_51_4,[],compView_51);
    this._text_52 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_53 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_53,'floating','');
    this._Label_53_3 = new import20.Label(this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_53),this.renderer,'',(null as any),(null as any),(null as any));
    this._text_54 = this.renderer.createText(this._el_53,'Confirm Password',(null as any));
    this._text_55 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_56 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_56,'name','confirmpassword');
    this.renderer.setElementAttribute(this._el_56,'ng-change','view.confirmPassword()');
    this.renderer.setElementAttribute(this._el_56,'ng-model','view.confirmpassword');
    this.renderer.setElementAttribute(this._el_56,'required','');
    this.renderer.setElementAttribute(this._el_56,'type','password');
    this._appEl_56 = new import2.AppElement(56,51,this,this._el_56);
    var compView_56:any = import36.viewFactory_TextInput0(this.viewUtils,this.injector(56),this._appEl_56);
    this._TextInput_56_4 = new import21.TextInput(this.parentInjector.get(import23.Config),this.parentInjector.get(import35.Form),this._Item_51_4,this.parentInjector.get(import27.App),this.parentInjector.get(import37.Platform),new import24.ElementRef(this._el_56),this.renderer,this._Content_9_4,this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import38.NgControl,(null as any)));
    this._appEl_56.initComponent(this._TextInput_56_4,[],compView_56);
    this._text_57 = this.renderer.createText((null as any),'\n                ',(null as any));
    compView_56.create(this._TextInput_56_4,[],(null as any));
    this._text_58 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._query_Label_51_0.reset([this._Label_53_3]);
    this._Item_51_4.contentLabel = this._query_Label_51_0.first;
    compView_51.create(this._Item_51_4,[
      [],
      [].concat([this._el_53]),
      [].concat([
        this._text_52,
        this._text_55,
        this._text_58
      ]
      ),
      [].concat([this._el_56]),
      []
    ]
    ,(null as any));
    this._text_59 = this.renderer.createText(this._el_13,'\n            \n            ',(null as any));
    this._el_60 = this.renderer.createElement(this._el_13,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_60,'class','textbox-background mob-content-center item item-block');
    this._appEl_60 = new import2.AppElement(60,13,this,this._el_60);
    var compView_60:any = import34.viewFactory_Item0(this.viewUtils,this.injector(60),this._appEl_60);
    this._Item_60_4 = new import18.Item(this.parentInjector.get(import35.Form),this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_60),this.renderer);
    this._ItemContent_60_5 = new import18.ItemContent();
    this._query_Label_60_0 = new import19.QueryList<any>();
    this._query_Button_60_1 = new import19.QueryList<any>();
    this._query_Icon_60_2 = new import19.QueryList<any>();
    this._appEl_60.initComponent(this._Item_60_4,[],compView_60);
    this._text_61 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_62 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_62,'floating','');
    this._Label_62_3 = new import20.Label(this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_62),this.renderer,'',(null as any),(null as any),(null as any));
    this._text_63 = this.renderer.createText(this._el_62,'Mobile',(null as any));
    this._text_64 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_65 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_65,'name','mobile');
    this.renderer.setElementAttribute(this._el_65,'ng-change','view.onChange(\'mobile\')');
    this.renderer.setElementAttribute(this._el_65,'ng-maxlength','10');
    this.renderer.setElementAttribute(this._el_65,'ng-minlength','10');
    this.renderer.setElementAttribute(this._el_65,'ng-model','view.mobile');
    this.renderer.setElementAttribute(this._el_65,'required','');
    this.renderer.setElementAttribute(this._el_65,'type','tel');
    this._appEl_65 = new import2.AppElement(65,60,this,this._el_65);
    var compView_65:any = import36.viewFactory_TextInput0(this.viewUtils,this.injector(65),this._appEl_65);
    this._TextInput_65_4 = new import21.TextInput(this.parentInjector.get(import23.Config),this.parentInjector.get(import35.Form),this._Item_60_4,this.parentInjector.get(import27.App),this.parentInjector.get(import37.Platform),new import24.ElementRef(this._el_65),this.renderer,this._Content_9_4,this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import38.NgControl,(null as any)));
    this._appEl_65.initComponent(this._TextInput_65_4,[],compView_65);
    this._text_66 = this.renderer.createText((null as any),'\n                ',(null as any));
    compView_65.create(this._TextInput_65_4,[],(null as any));
    this._text_67 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._query_Label_60_0.reset([this._Label_62_3]);
    this._Item_60_4.contentLabel = this._query_Label_60_0.first;
    compView_60.create(this._Item_60_4,[
      [],
      [].concat([this._el_62]),
      [].concat([
        this._text_61,
        this._text_64,
        this._text_67
      ]
      ),
      [].concat([this._el_65]),
      []
    ]
    ,(null as any));
    this._text_68 = this.renderer.createText(this._el_13,'\n    \n        ',(null as any));
    this._text_69 = this.renderer.createText(this._el_11,'\n        \n    ',(null as any));
    this._text_70 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_71 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_71,'class','bar bar-footer background-color registration-footer mob-content-center');
    this._text_72 = this.renderer.createText(this._el_71,'\n        ',(null as any));
    this._el_73 = this.renderer.createElement(this._el_71,'button',(null as any));
    this.renderer.setElementAttribute(this._el_73,'class','button-background');
    this.renderer.setElementAttribute(this._el_73,'form','nameform');
    this.renderer.setElementAttribute(this._el_73,'ion-button','');
    this.renderer.setElementAttribute(this._el_73,'ng-click','view.registerNewUser(view.registrationForm)');
    this._appEl_73 = new import2.AppElement(73,71,this,this._el_73);
    var compView_73:any = import39.viewFactory_Button0(this.viewUtils,this.injector(73),this._appEl_73);
    this._Button_73_4 = new import22.Button((null as any),'',this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_73),this.renderer);
    this._appEl_73.initComponent(this._Button_73_4,[],compView_73);
    this._text_74 = this.renderer.createText((null as any),'Sign Up',(null as any));
    compView_73.create(this._Button_73_4,[[].concat([this._text_74])],(null as any));
    this._text_75 = this.renderer.createText(this._el_71,'\n    ',(null as any));
    this._text_76 = this.renderer.createText((null as any),'\n',(null as any));
    compView_9.create(this._Content_9_4,[
      [],
      [].concat([
        this._text_10,
        this._el_11,
        this._text_70,
        this._el_71,
        this._text_76
      ]
      ),
      []
    ]
    ,(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_11,'submit',this.eventHandler(this._handle_submit_11_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_11,'reset',this.eventHandler(this._handle_reset_11_1.bind(this)));
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    this._expr_16 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._text_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._text_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._text_49,
      this._text_50,
      this._el_51,
      this._text_52,
      this._el_53,
      this._text_54,
      this._text_55,
      this._el_56,
      this._text_57,
      this._text_58,
      this._text_59,
      this._el_60,
      this._text_61,
      this._el_62,
      this._text_63,
      this._text_64,
      this._el_65,
      this._text_66,
      this._text_67,
      this._text_68,
      this._text_69,
      this._text_70,
      this._el_71,
      this._text_72,
      this._el_73,
      this._text_74,
      this._text_75,
      this._text_76
    ]
    ,[
      disposable_0,
      disposable_1
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.ToolbarTitle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._ToolbarTitle_4_4; }
    if (((token === import12.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._Navbar_2_4; }
    if (((token === import11.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Header_0_3; }
    if (((token === import20.Label) && ((17 <= requestNodeIndex) && (requestNodeIndex <= 18)))) { return this._Label_17_3; }
    if (((token === import21.TextInput) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._TextInput_20_4; }
    if (((token === import18.Item) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._Item_15_4; }
    if (((token === import18.ItemContent) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._ItemContent_15_5; }
    if (((token === import20.Label) && ((26 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._Label_26_3; }
    if (((token === import21.TextInput) && ((29 <= requestNodeIndex) && (requestNodeIndex <= 30)))) { return this._TextInput_29_4; }
    if (((token === import18.Item) && ((24 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._Item_24_4; }
    if (((token === import18.ItemContent) && ((24 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._ItemContent_24_5; }
    if (((token === import20.Label) && ((35 <= requestNodeIndex) && (requestNodeIndex <= 36)))) { return this._Label_35_3; }
    if (((token === import21.TextInput) && ((38 <= requestNodeIndex) && (requestNodeIndex <= 39)))) { return this._TextInput_38_4; }
    if (((token === import18.Item) && ((33 <= requestNodeIndex) && (requestNodeIndex <= 40)))) { return this._Item_33_4; }
    if (((token === import18.ItemContent) && ((33 <= requestNodeIndex) && (requestNodeIndex <= 40)))) { return this._ItemContent_33_5; }
    if (((token === import20.Label) && ((44 <= requestNodeIndex) && (requestNodeIndex <= 45)))) { return this._Label_44_3; }
    if (((token === import21.TextInput) && ((47 <= requestNodeIndex) && (requestNodeIndex <= 48)))) { return this._TextInput_47_4; }
    if (((token === import18.Item) && ((42 <= requestNodeIndex) && (requestNodeIndex <= 49)))) { return this._Item_42_4; }
    if (((token === import18.ItemContent) && ((42 <= requestNodeIndex) && (requestNodeIndex <= 49)))) { return this._ItemContent_42_5; }
    if (((token === import20.Label) && ((53 <= requestNodeIndex) && (requestNodeIndex <= 54)))) { return this._Label_53_3; }
    if (((token === import21.TextInput) && ((56 <= requestNodeIndex) && (requestNodeIndex <= 57)))) { return this._TextInput_56_4; }
    if (((token === import18.Item) && ((51 <= requestNodeIndex) && (requestNodeIndex <= 58)))) { return this._Item_51_4; }
    if (((token === import18.ItemContent) && ((51 <= requestNodeIndex) && (requestNodeIndex <= 58)))) { return this._ItemContent_51_5; }
    if (((token === import20.Label) && ((62 <= requestNodeIndex) && (requestNodeIndex <= 63)))) { return this._Label_62_3; }
    if (((token === import21.TextInput) && ((65 <= requestNodeIndex) && (requestNodeIndex <= 66)))) { return this._TextInput_65_4; }
    if (((token === import18.Item) && ((60 <= requestNodeIndex) && (requestNodeIndex <= 67)))) { return this._Item_60_4; }
    if (((token === import18.ItemContent) && ((60 <= requestNodeIndex) && (requestNodeIndex <= 67)))) { return this._ItemContent_60_5; }
    if (((token === import17.List) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 68)))) { return this._List_13_3; }
    if (((token === import15.NgForm) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 69)))) { return this._NgForm_11_3; }
    if (((token === import40.ControlContainer) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 69)))) { return this._ControlContainer_11_4; }
    if (((token === import16.NgControlStatusGroup) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 69)))) { return this._NgControlStatusGroup_11_5; }
    if (((token === import22.Button) && ((73 <= requestNodeIndex) && (requestNodeIndex <= 74)))) { return this._Button_73_4; }
    if (((token === import14.Content) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 76)))) { return this._Content_9_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_9_4.ngOnInit(); }
    const currVal_11:any = 'text';
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this._TextInput_20_4.type = currVal_11;
      this._expr_11 = currVal_11;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._TextInput_20_4.ngOnInit(); }
    const currVal_12:any = 'text';
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this._TextInput_29_4.type = currVal_12;
      this._expr_12 = currVal_12;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._TextInput_29_4.ngOnInit(); }
    const currVal_13:any = 'text';
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this._TextInput_38_4.type = currVal_13;
      this._expr_13 = currVal_13;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._TextInput_38_4.ngOnInit(); }
    const currVal_14:any = 'password';
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this._TextInput_47_4.type = currVal_14;
      this._expr_14 = currVal_14;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._TextInput_47_4.ngOnInit(); }
    const currVal_15:any = 'password';
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this._TextInput_56_4.type = currVal_15;
      this._expr_15 = currVal_15;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._TextInput_56_4.ngOnInit(); }
    const currVal_16:any = 'tel';
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this._TextInput_65_4.type = currVal_16;
      this._expr_16 = currVal_16;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._TextInput_65_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_15_1.dirty) {
        this._query_Button_15_1.reset([]);
        this._Item_15_4._buttons = this._query_Button_15_1;
        this._query_Button_15_1.notifyOnChanges();
      }
      if (this._query_Icon_15_2.dirty) {
        this._query_Icon_15_2.reset([]);
        this._Item_15_4._icons = this._query_Icon_15_2;
        this._query_Icon_15_2.notifyOnChanges();
      }
      if (this._query_Button_24_1.dirty) {
        this._query_Button_24_1.reset([]);
        this._Item_24_4._buttons = this._query_Button_24_1;
        this._query_Button_24_1.notifyOnChanges();
      }
      if (this._query_Icon_24_2.dirty) {
        this._query_Icon_24_2.reset([]);
        this._Item_24_4._icons = this._query_Icon_24_2;
        this._query_Icon_24_2.notifyOnChanges();
      }
      if (this._query_Button_33_1.dirty) {
        this._query_Button_33_1.reset([]);
        this._Item_33_4._buttons = this._query_Button_33_1;
        this._query_Button_33_1.notifyOnChanges();
      }
      if (this._query_Icon_33_2.dirty) {
        this._query_Icon_33_2.reset([]);
        this._Item_33_4._icons = this._query_Icon_33_2;
        this._query_Icon_33_2.notifyOnChanges();
      }
      if (this._query_Button_42_1.dirty) {
        this._query_Button_42_1.reset([]);
        this._Item_42_4._buttons = this._query_Button_42_1;
        this._query_Button_42_1.notifyOnChanges();
      }
      if (this._query_Icon_42_2.dirty) {
        this._query_Icon_42_2.reset([]);
        this._Item_42_4._icons = this._query_Icon_42_2;
        this._query_Icon_42_2.notifyOnChanges();
      }
      if (this._query_Button_51_1.dirty) {
        this._query_Button_51_1.reset([]);
        this._Item_51_4._buttons = this._query_Button_51_1;
        this._query_Button_51_1.notifyOnChanges();
      }
      if (this._query_Icon_51_2.dirty) {
        this._query_Icon_51_2.reset([]);
        this._Item_51_4._icons = this._query_Icon_51_2;
        this._query_Icon_51_2.notifyOnChanges();
      }
      if (this._query_Button_60_1.dirty) {
        this._query_Button_60_1.reset([]);
        this._Item_60_4._buttons = this._query_Button_60_1;
        this._query_Button_60_1.notifyOnChanges();
      }
      if (this._query_Icon_60_2.dirty) {
        this._query_Icon_60_2.reset([]);
        this._Item_60_4._icons = this._query_Icon_60_2;
        this._query_Icon_60_2.notifyOnChanges();
      }
      this._TextInput_20_4.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_15_4.ngAfterContentInit(); }
      this._TextInput_29_4.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_24_4.ngAfterContentInit(); }
      this._TextInput_38_4.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_33_4.ngAfterContentInit(); }
      this._TextInput_47_4.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_42_4.ngAfterContentInit(); }
      this._TextInput_56_4.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_51_4.ngAfterContentInit(); }
      this._TextInput_65_4.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_60_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_73_4.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Navbar_2_4._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_2_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Content_9_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_9,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_5:any = this._NgControlStatusGroup_11_5.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_11,'ng-untouched',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this._NgControlStatusGroup_11_5.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_11,'ng-touched',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._NgControlStatusGroup_11_5.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_11,'ng-pristine',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatusGroup_11_5.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_11,'ng-dirty',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._NgControlStatusGroup_11_5.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_11,'ng-valid',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this._NgControlStatusGroup_11_5.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_11,'ng-invalid',currVal_10);
      this._expr_10 = currVal_10;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._TextInput_20_4.ngOnDestroy();
    this._TextInput_29_4.ngOnDestroy();
    this._TextInput_38_4.ngOnDestroy();
    this._TextInput_47_4.ngOnDestroy();
    this._TextInput_56_4.ngOnDestroy();
    this._TextInput_65_4.ngOnDestroy();
    this._Content_9_4.ngOnDestroy();
  }
  private _handle_submit_11_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_11_3.onSubmit()) !== false);
    return (true && pd_0);
  }
  private _handle_reset_11_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_11_3.onReset()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_RegistrationPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.RegistrationPage> {
  if ((renderType_RegistrationPage === (null as any))) { (renderType_RegistrationPage = viewUtils.createRenderComponentType('/Users/mackalvin/Downloads/ISI-V2/.tmp/pages/registration/registration.html',0,import9.ViewEncapsulation.None,styles_RegistrationPage,{})); }
  return new _View_RegistrationPage0(viewUtils,parentInjector,declarationEl);
}